# Custom Language File for Launcher Customizer

[ejs.app]
title = "MREPUBLIK Launcher"

[ejs.landing]
mediaGitHubURL = "https://mrepublik.co.uk/"
mediaInstagramURL = "https://www.instagram.com/mrepublik_mc/"
mediaYouTubeURL = "https://www.youtube.com/channel/UCIU9X5KHmf_kv7iyo_CrZwQ"
mediaDiscordURL = "https://discord.gg/9czpaHDQVV"

[ejs.settings]
sourceGithubLink = "https://github.com/snoweyrawr/MREPUBLIKLauncher"
supportLink = "https://github.com/snoweyrawr/MREPUBLIKLauncher/issues"
